Miner:
  #Currency in which crypto will be converted
  cryptocurrency: "usd"
  #Miner repair cost
  repairCost: 10000.0
  #how much do you dig per minute
  perMinuteMine: 0.00005
  #How much damage does miner take per minute.
  damageRange:
    min: 0.03
    max: 0.1
  #No matter how far away a player is.
  #NOTE: (Performance problems may occur if you go above 20 blocks)
  checkPlayerRadius: 20
  #Check every few minutes if there is a player nearby.
  #NOTE: (Performance issues may start if you go under 15 minutes)
  checkPlayerMinute: 15
  #You can activate it to reduce server lag and memory usage.
  delete-unused-Miners:
    Status: false
    #You must enter in days.
    Time: 30